version: '3.5'

services:
  broker0:
    build: ./Mosquitto
    image: fuzzing-broker
    mac_address: 00:00:00:00:00:02
    networks:
      fuzznet:
        ipv4_address: 192.168.100.5
    container_name: broker0

networks:
  fuzznet:
    name: fuzznet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24