version: '3.5'

services:
  broker0:
    build: ./Mosquitto
    image: fuzzing-broker
    mac_address: 00:00:00:00:00:02
    networks:
      fuzznet:
        ipv4_address: 192.168.100.5
    container_name: broker0

  broker1:
    image: fuzzing-broker
    mac_address: 00:00:00:00:00:03
    networks:
      fuzznet:
        ipv4_address: 192.168.100.6
    container_name: broker1

  broker2:
    image: fuzzing-broker
    mac_address: 00:00:00:00:00:04
    networks:
      fuzznet:
        ipv4_address: 192.168.100.7
    container_name: broker2

networks:
  fuzznet:
    name: fuzznet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24